# Sensor kit calibration for Leo Drive Bus-ODD (Isuzu bus)
# Note: For rosbag playback, TF data comes from the recorded /tf_static topic
# These values are placeholders based on typical bus sensor configurations

sensor_kit_base_link:
  # LiDARs: 1x VLP16 (front) + 2x VLP32C (left, right)
  velodyne_front_base_link:
    x: 2.0
    y: 0.0
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_left_base_link:
    x: 0.0
    y: 1.2
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: 1.5708  # 90 degrees
  velodyne_right_base_link:
    x: 0.0
    y: -1.2
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: -1.5708  # -90 degrees

  # Cameras: 3x Lucid Vision Triton 5.4MP
  lucid_camera_0/camera_link:
    x: 2.0
    y: 0.5
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lucid_camera_1/camera_link:
    x: 2.0
    y: -0.5
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lucid_camera_2/camera_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # GNSS/INS: Applanix POS LV 120
  gnss_link:
    x: 0.0
    y: 0.0
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # IMU (from Applanix)
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
